name: App Dev Build
on:
  push:
    branches: [ master/prod, debug/dev ]
  pull_request: 
    branches: [ master/prod, debug/dev ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: "2.18.0"
          channel: "beta"

      - name: Upgrade Dart
        run: dart pub get
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Start release build
        run: flutter build appbundle
