name: App Dev Build
on:
  push:
    branches: [ master/prod, debug/dev ]
  pull_request: 
    branches: [ master/prod, debug/dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: update flutter
        run: flutter upgrade -v

      - name: Get dependencies
        run: flutter pub get
        
      - name: Start release build
        run: flutter build appbundle
