name: App Dev Build
on:
  push:
    branches: [ prod, debug/dev, dev ]
  pull_request: 
    branches: [ prod, debug/dev, dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: update flutter
        run: flutter upgrade -v

      - name: Get dependencies
        run: flutter pub get
        
      - name: Start release build
        run: flutter build appbundle 
        
      - name: Run linting
        run: flutter analyze

      - name: Run tests
        run: flutter test test
        
      - name: Integration tests
        run: flutter test integration_test
